"""add_google_oauth_fields_to_user

Revision ID: 36929e0b4754
Revises: 9da02619a4fe
Create Date: 2025-10-22 17:04:00.174089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36929e0b4754'
down_revision: Union[str, Sequence[str], None] = '9da02619a4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('provider', sa.String(length=20), nullable=True))
    
    # Atualizar usuários existentes para ter provider 'local'
    op.execute("UPDATE users SET provider = 'local' WHERE provider IS NULL")
    
    # Criar índices
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
