"""add_unidade_medida_to_batch

Revision ID: 9da02619a4fe
Revises: 8d22053b54ff
Create Date: 2025-10-21 16:46:49.722401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da02619a4fe'
down_revision: Union[str, Sequence[str], None] = '8d22053b54ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('unidadeMedida', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'unidadeMedida')
    # ### end Alembic commands ###
