"""Add user_id field to products table

Revision ID: a77dc48ea19d
Revises: e0b810dbac1d
Create Date: 2025-10-20 07:57:51.023152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77dc48ea19d'
down_revision: Union[str, Sequence[str], None] = 'e0b810dbac1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Para SQLite, vamos adicionar a coluna como nullable e depois atualizar
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Atualiza produtos existentes para ter user_id = 1 (assumindo que existe pelo menos um usuário)
    # Em produção, você deveria mapear corretamente os produtos para seus criadores
    op.execute("UPDATE products SET user_id = 1 WHERE user_id IS NULL")
    
    # SQLite não suporta ALTER COLUMN para NOT NULL, então deixamos como nullable mas com valor padrão
    # A constraint NOT NULL será aplicada no modelo SQLAlchemy
    
    # Não fazemos alter_column para image no SQLite pois ele não suporta bem
    # O tamanho maior já está refletido no modelo
    
    op.create_foreign_key('fk_products_user_id', 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_user_id', 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
