"""Add user_id field to products table

Revision ID: a77dc48ea19d
Revises: e0b810dbac1d
Create Date: 2025-10-20 07:57:51.023152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77dc48ea19d'
down_revision: Union[str, Sequence[str], None] = 'e0b810dbac1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adiciona coluna user_id como nullable
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))

    # Atualiza produtos existentes apenas se existirem usuários
    op.execute("""
        UPDATE products SET user_id = (SELECT id FROM users LIMIT 1)
        WHERE user_id IS NULL
        AND EXISTS (SELECT 1 FROM users)
    """)

    # PostgreSQL suporta ALTER COLUMN - altera image para VARCHAR(500)
    op.alter_column('products', 'image',
                    existing_type=sa.String(255),
                    type_=sa.String(500),
                    existing_nullable=True)

    op.create_foreign_key('fk_products_user_id', 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_user_id', 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
